name: BatteryStatus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  json_annotation: any
  
  hooks_riverpod: any
  
  flutter_hooks: any
  
  go_router: any
  
  freezed_annotation: any
  
  loader_overlay: any
  liquid_progress_indicator: ^0.4.0
  flutter_spinkit: ^5.1.0
  another_flushbar: ^1.12.29
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  build_runner: any
  freezed: any
  json_serializable: any
  custom_lint: any 
  riverpod_lint: any


flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  web: false
  image: "splash.png"
  android_12:
    color: "#ffffff"
    icon_background_color: "#ffffff"
    
    
 
flutter_icons:
  android: true
  ios: true
  image_path: "launcher.png"
  image_path_ios: "launcher.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "launcher.png"
  remove_alpha_ios: true
  min_sdk_android: 21 

# flutter pub run flutter_launcher_icons
flutter:

  uses-material-design: true

  # assets:
  #   - assets/
  #   - fonts/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
